import { ChevronDown, ChevronLeft, ChevronRight, Pencil, Plus, Search } from "lucide-react";
import { useMemo, useState } from "react";
import ContextMenu from "./ContextMenu";

const text = (value) => String(value ?? "").toLocaleLowerCase("es");

export default function ConsolidatedView({ anios, aprendizajes, cursos, competencias, capacidades, loading, onEditLearning, onEditCompetency, onAddCapacity, onEditCapacity }) {
  const [query, setQuery] = useState(""), [year, setYear] = useState(""), [course, setCourse] = useState("");
  const [expanded, setExpanded] = useState(new Set());
  const [mobile, setMobile] = useState({ level: "learning", learning: null, course: null, competency: null });
  const years = useMemo(() => new Map(anios.map((x) => [String(x.id_anio_lectivo), x])), [anios]);
  const normalized = text(query.trim());
  const toggle = (key) => setExpanded((current) => { const next = new Set(current); next.has(key) ? next.delete(key) : next.add(key); return next; });
  const competencyMatches = (item) => !normalized || text(`${item.codigo} ${item.descripcion}`).includes(normalized) || capacidades.some((x) => String(x.id_competencia) === String(item.id_competencia) && text(x.descripcion).includes(normalized));
  const courseMatches = (item, learning) => {
    if (course && String(item.id_curso) !== String(course)) return false;
    if (!normalized || text(item.nombre).includes(normalized) || text(learning.nombre_aprendizaje).includes(normalized) || text(years.get(String(learning.id_anio_lectivo))?.anio).includes(normalized)) return true;
    return competencias.some((x) => String(x.id_curso) === String(item.id_curso) && String(x.id_aprendizaje) === String(learning.id_aprendizaje) && competencyMatches(x));
  };
  const visibleLearnings = aprendizajes.filter((learning) => (!year || String(learning.id_anio_lectivo) === String(year)) && cursos.some((item) => String(item.id_anio_lectivo) === String(learning.id_anio_lectivo) && courseMatches(item, learning)));
  const filteredCourses = (learning) => cursos.filter((item) => String(item.id_anio_lectivo) === String(learning.id_anio_lectivo) && courseMatches(item, learning));
  const filteredCompetencies = (learning, itemCourse) => competencias.filter((item) => String(item.id_aprendizaje) === String(learning.id_aprendizaje) && String(item.id_curso) === String(itemCourse.id_curso) && competencyMatches(item));
  const capacitiesOf = (competency) => capacidades.filter((item) => String(item.id_competencia) === String(competency.id_competencia) && (!normalized || text(item.descripcion).includes(normalized) || text(`${competency.codigo} ${competency.descripcion}`).includes(normalized)));
  const context = (learning, itemCourse, competency = null) => ({ year: String(learning.id_anio_lectivo), aprendizaje: String(learning.id_aprendizaje), curso: String(itemCourse?.id_curso || ""), competencia: String(competency?.id_competencia || "") });

  const filters = <div className="consolidated-filters"><label className="tree-search"><Search size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar curso, competencia o capacidad..." /></label><select value={year} onChange={(e) => { setYear(e.target.value); setCourse(""); }}><option value="">Todos los años / aprendizajes</option>{anios.map((x) => <option key={x.id_anio_lectivo} value={x.id_anio_lectivo}>{x.anio}</option>)}</select><select value={course} onChange={(e) => setCourse(e.target.value)}><option value="">Todos los cursos</option>{cursos.filter((x) => !year || String(x.id_anio_lectivo) === String(year)).map((x) => <option key={x.id_curso} value={x.id_curso}>{x.nombre}</option>)}</select></div>;

  return <div className="consolidated-view">{filters}
    <div className="academic-tree-desktop">{visibleLearnings.map((learning) => { const learningKey = `l-${learning.id_aprendizaje}`; return <article className="tree-learning" key={learningKey}><div className="tree-row tree-row--learning"><button className="tree-toggle" onClick={() => toggle(learningKey)}>{expanded.has(learningKey) ? <ChevronDown /> : <ChevronRight />}</button><strong>{learning.nombre_aprendizaje}</strong><small>{years.get(String(learning.id_anio_lectivo))?.anio}</small><ContextMenu actions={[{ label: "Editar", icon: <Pencil size={14} />, onClick: () => onEditLearning(learning, context(learning)) }]} /></div>{expanded.has(learningKey) && <div className="tree-children">{filteredCourses(learning).map((itemCourse) => { const courseKey = `${learningKey}-c-${itemCourse.id_curso}`; return <div key={courseKey}><div className="tree-row tree-row--course"><button className="tree-toggle" onClick={() => toggle(courseKey)}>{expanded.has(courseKey) ? <ChevronDown /> : <ChevronRight />}</button><strong>{itemCourse.nombre}</strong></div>{expanded.has(courseKey) && <div className="tree-competencies">{filteredCompetencies(learning, itemCourse).map((competency) => { const key = `co-${competency.id_competencia}`; return <div key={key}><div className="tree-row tree-row--competency"><button className="tree-toggle" onClick={() => toggle(key)}>{expanded.has(key) ? <ChevronDown /> : <ChevronRight />}</button><span><b>{competency.codigo || "—"}</b> · {competency.descripcion}</span><ContextMenu actions={[{ label: "Editar", icon: <Pencil size={14} />, onClick: () => onEditCompetency(competency, context(learning, itemCourse, competency)) }, { label: "Agregar capacidad", icon: <Plus size={14} />, onClick: () => onAddCapacity(context(learning, itemCourse, competency)) }]} /></div>{expanded.has(key) && <div className="tree-capacities">{capacitiesOf(competency).map((capacity) => <div className="tree-row tree-row--capacity" key={capacity.id_capacidad}><span>{capacity.descripcion}</span><ContextMenu actions={[{ label: "Editar", icon: <Pencil size={14} />, onClick: () => onEditCapacity(capacity, context(learning, itemCourse, competency)) }]} /></div>)}{!capacitiesOf(competency).length && <p>No hay capacidades registradas.</p>}</div>}</div>; })}{!filteredCompetencies(learning, itemCourse).length && <p className="tree-empty">No hay competencias registradas para este curso.</p>}</div>}</div>; })}</div>}</article>; })}{!loading && !visibleLearnings.length && <p className="parameter-empty">No se encontraron elementos configurados.</p>}</div>
    <div className="academic-tree-mobile">{mobile.level !== "learning" && <button className="mobile-back" onClick={() => setMobile((s) => s.level === "capacity" ? { ...s, level: "competency", competency: null } : s.level === "competency" ? { ...s, level: "course", course: null } : { level: "learning", learning: null, course: null, competency: null })}><ChevronLeft size={18} />Volver</button>}{mobile.level === "learning" && visibleLearnings.map((learning) => <button className="mobile-academic-row" key={learning.id_aprendizaje} onClick={() => setMobile({ level: "course", learning, course: null, competency: null })}><span><strong>{learning.nombre_aprendizaje}</strong><small>{years.get(String(learning.id_anio_lectivo))?.anio} · {filteredCourses(learning).length} cursos</small></span><ChevronRight /></button>)}{mobile.level === "course" && filteredCourses(mobile.learning).map((itemCourse) => <button className="mobile-academic-row" key={itemCourse.id_curso} onClick={() => setMobile((s) => ({ ...s, level: "competency", course: itemCourse }))}><span><strong>{itemCourse.nombre}</strong><small>{filteredCompetencies(mobile.learning, itemCourse).length} competencias</small></span><ChevronRight /></button>)}{mobile.level === "competency" && filteredCompetencies(mobile.learning, mobile.course).map((competency) => <button className="mobile-academic-row" key={competency.id_competencia} onClick={() => setMobile((s) => ({ ...s, level: "capacity", competency }))}><span><strong>{competency.codigo || "Competencia"}</strong><small>{competency.descripcion} · {capacitiesOf(competency).length} capacidades</small></span><ChevronRight /></button>)}{mobile.level === "capacity" && <><h3>{mobile.competency.codigo} · {mobile.competency.descripcion}</h3>{capacitiesOf(mobile.competency).map((capacity) => <div className="mobile-academic-row" key={capacity.id_capacidad}><span>{capacity.descripcion}</span><ContextMenu actions={[{ label: "Editar", icon: <Pencil size={14} />, onClick: () => onEditCapacity(capacity, context(mobile.learning, mobile.course, mobile.competency)) }]} /></div>)}</>}</div>
  </div>;
}
